<Project Sdk="Microsoft.NET.Sdk">
  <Sdk Name="Aspire.AppHost.Sdk" Version="13.1.0" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AlfredsForge.Gateway\AlfredsForge.Gateway.csproj" />
    <ProjectReference Include="..\AlfredsForge.Runtime\AlfredsForge.Runtime.csproj" />
  </ItemGroup>

</Project>
