<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Orleans.Server" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Workbench.Domain\Workbench.Domain.csproj" />
  </ItemGroup>

</Project>
